insensitive_pii = [
    "Account Name",
    "Marital Status",
    "Nationality",
    "Weight",
    "Search History",
    "Employment History",
    "Audio Recordings",
    "Video",
    "IoT or Sensor Data",
    "Video Recordings",
    "Technical Diagnostic Data",
    "Crash data",
    "License Plate",
    "Social Media Activity",
    "Social Media Contact",
    "Employee Code",
    "Date of Birth",
    "Age",
    "Gender",
    "Date of Birth",
    "Last Name",
    "First Name",
    "Photograph",
    "Expenses",
    "Company Allowances",
    "Salary",
    "Payment Mode",
    "Purchase History",
    "Offer Details",
    "Product Return History",
    "Order Details",
    "Address",
    "Phone Number",
    "Email Address",
    "Customer Support",
    "Reviews",
    "Emails or Text Messages",
    "Ratings",
    "Dependent Name",
    "Dependent Contact Details",
    "Spouse Name",
    "Advertising Identifiers",
    "MAC Address",
    "IP Address",
    "Device Identifier",
    "Cookies",
    "Social Media Login Identifier",
    "Account ID",
    "Language Preferences",
    "Account Name",
]

sensitive_pii = [
    "Disability or Specific Condition",
    "Social Security Number",
    "Passport",
    "Driving License",
    "Religion / Religious Beliefs",
    "Credit History",
    "Precise Location",
    "Facial Recognition",
    "Fingerprint Scans",
    "Voice Recognition",
    "Payroll Information",
    "Tax Information",
    "Card Number",
    "Bank Account Details",
    "Account Password",
]
